<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\Kalam-Regular.ttf" />
    <None Remove="Images\BG.PNG" />
    <None Remove="Images\codememologo.ico" />
    <None Remove="Images\createButton.PNG" />
    <None Remove="Images\keybindButton.PNG" />
    <None Remove="Images\selectedButton.PNG" />
    <None Remove="Images\unselectedButton.PNG" />
    <None Remove="Sounds\click.wav" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="MVVM\View\" />
    <Folder Include="MVVM\ViewModel\" />
    <Folder Include="MVVM\Model\" />
    <Folder Include="Theme\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\Kalam-Regular.ttf" />
    <Resource Include="Images\BG.PNG" />
    <Resource Include="Images\codememologo.ico" />
    <Resource Include="Images\createButton.PNG" />
    <Resource Include="Images\keybindButton.PNG" />
    <Resource Include="Images\selectedButton.PNG" />
    <Resource Include="Images\unselectedButton.PNG" />
    <Content Include="Sounds\click.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
